### ISSUE TITLE
Bug: Not mentioning that file will be overwritten

### ISSUE THREAD

**Issue by fenilgmehta** [linuxmint/warpinator#168]
Hi team, I found a bug where the message that `Files may be overwritten` is not behaving as expected.

Using warpinator v1.4.5 on the receiver side.

### Case 1

**Steps to reproduce**

1. Consider two devices A and B. Consider the file F.
2. Fully transfer the file F from A to B using warpinator.
3. Again request transfer of the same file F from A to B. Just notice that `Files may be overwritten` message is shown.
4. Now, cancel/reject the transfer from A/B respectively (any one is fine)
5. Delete the received file F from device B
6. Re-request for transfer from A
7. In device B, notice that `Files may be overwritten` message is still being shown.

### Case 2

**Steps to reproduce**

1. Consider two devices A and B. Consider the file F.
2. Start transfer of the file F from A to B using warpinator. Cancel the transfer from A after about half of the transfer is over.
3. Again request transfer of the same file F from A to B using the button shown in the below image
    ![image](https://user-images.githubusercontent.com/42742240/226089508-bd4d1b2d-9189-4079-871e-681f6f147520.png)
4. Notice that `Files may be overwritten` message is not shown

**Comment by mtwebster** [comment]
Hi,

I can't reproduce either of the cases in the latest version.

This seems mainly due to some recent security-related changes involving how cancelled and overwritten files are handled:
- A cancelled transfer will clean up after itself (remove those files that were already sent before cancellation).
- If overwriting existing files, they are removed prior to the transfer starting.
