### ISSUE TITLE
add a toggle switch for Secure Mode

### ISSUE THREAD

**Issue by niwla23** [linuxmint/warpinator#171]
Today I saw that warpinator now asks me to setup a group code. If I understand correctly, this will not allow me to share with people using another code. While I can see that you don't want to be spammed with files in public wifis (or what are the problems with having it in insecure mode?) I also think that it limits the usability as you can't quickly send a file to someone else (kina like airdop)

So why not add a little toggle in the top bar to enable Insecure Mode (maybe rename it to Public Mode then)? Otherwise you would have to go to settings, back up your group code, change it to "Warpinator", send the file and change it back to your original group code.

**Comment by mtwebster** [comment]
Nothing has really changed here - you've already got a group code - "Warpinator". All we're after here is to get people to change it to something else as soon as they can. If you have three computers on your network you like to send files between, just come up with a new code, and change those three machines to use it. That's it, you never have to change anything else.

Consider:
- You've got those three computers on a network, all using the default group code - 'Warpinator'. They can all send files to one another, etc..
- Maybe, since they're all in your home, you go into preferences and turn off 'Require approval before accepting files' on all of them so you don't have to hop between computers to accept your own files.
- Now, let's say that by some chance someone is able to get on your wifi. They fire up Warpinator, and are able to see those other three computers because they're all using the default group code, 'Warpinator' and can send anything they want to your computers (since you disabled approvals), and possibly fill up your hard drive in the process.

If you have a unique group code among your computers, this scenario can't happen, since their group code is 'Warpinator' and yours aren't. They're blind your machines.

This is all we're trying to accomplish here. It's the same reasoning as not keeping some 'default' password on a router or some other device - anyone can figure it out by googling 'default netscreen router password'.

You can still use warpinator with the default code, but it puts limitations on it to keep unsafe things from happening, like not allowing approvals to be disabled and preventing Warpinator from autostarting.

**Comment by niwla23** [comment]
> You can still use warpinator with the default code, but it puts limitations on it to keep unsafe things from happening, like not allowing approvals to be disabled and preventing Warpinator from autostarting.

This is what I meant the toggle for. The toggle would internally just save the current code and then use "Warpinator" instead while being on. After switching it off again it would use the old, manually configured code again. This would enable you to easily share files with guests in your wifi if both simply enable the public sharing mode.
