### ISSUE TITLE
Linux Mint Warpinator Stolen

### ISSUE THREAD

**Issue by Tenebris-Umbra** [linuxmint/warpinator#215]
### Distribution

World Wide WEb

### Package version

ALl

### Frequency

Always

### Bug description

https://warpinator.com/

Is taking credit for Wapinator App, there is no mention of Linux Mint or it's dev's or any license 

### Steps to reproduce

theft

### Expected behavior

theft

### Additional information

theft

**Comment by carlosmintfan** [comment]
I'll report them to Mozilla, these thieves!

**Comment by carlosmintfan** [comment]
(Context for closing: site is down now.)

**Comment by leigh123linux** [comment]
It moved to https://warpinator.net/

**Comment by carlosmintfan** [comment]
Aaaaargh! But they're only half-faking now. They say it's developed by Linux Mint but call their Android edition official.
And what about "In the Android domain, an unofficial edition of Kavita is accessible"?? What's Kavita?

**Comment by carlosmintfan** [comment]
And they capitalise WarPinator. Oh yeah. It pinates wars.

**Comment by carlosmintfan** [comment]
"It seems like there might be a slight error in your question. It’s possible that you’re referring to “WinZip” instead of “Winpinator.” WinZip is a popular file compression and archive utility for Windows. If you’re looking for information on WinZip, you can visit the official WinZip website to download and learn more about the application: WinZip Official Website."

Hahahahahahahahahahahahahaha!!!! That's what happens when using AI too much without without being vigilant. LOL

**Comment by carlosmintfan** [comment]
> Warpinator is a utility software developed by the Windows & Linux distribution Mint
Wow! I never knew Mint is not only a Linux but also a Windows distribution!!!

**Comment by macropin** [comment]
Please reopen. 

https://warpinator.com/ is back.

**Comment by Lanchon** [comment]
btw, see this:

> Open-source project impersonation
> https://gist.github.com/zerobitflux/57f3791086e18481030df9c204b323fe
