### ISSUE TITLE
Warpinator cannot save to or send from many locations including additional disks

### ISSUE THREAD

**Issue by shag00** [linuxmint/warpinator#67]
Version: stable , released on 14/8/20

On the PC i wish to save to (Kubuntu 20.04), location for recieved files>other, there are a hodhepodge of locations that warpinator recognises at root, 14 in my case out of 24 directories, for example it recognises /etc but not /media.

A similar situation exists to the sending machine (Kubuntu 20.10) so I cannot send what I need to send,

There appears to be no way to type in a location that connects to the file browser, ie, if I create a new directory /media and click on it there are no files or directories.

**Comment by mtwebster** [comment]
How did you install this? Via flatpak or a ppa or built? These issues sound like you're using the flatpak version.

**Comment by shag00** [comment]
flatpak

**Comment by mtwebster** [comment]
Unfortunately due to how flatpak works, only the user's home folder is fully accessible in this case.

If you need access to the entire computer, you'll need to install the 'full version' of warpinator.  Being on an ubuntu derivative, you should be able to just install this: http://packages.linuxmint.com/pool/backport/w/warpinator/warpinator_1.0.8+ulyana_all.deb.

There there will be some additional dependencies to install (depending on how you install it these may be added automatically, or you might need to do something like run `apt install -f` to install them after.

**Comment by shag00** [comment]
Problem solved
